apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app.kubernetes.io/name: portfolio
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
